-- Insert queries
-- https://genesis.usp.ac.fj/phpmyadmin/

-- Q1

SELECT CANDIDATE.CAND_LNAME, QUALIFICATION.QUAL_DESCRIPTION
FROM CANDIDATE
LEFT JOIN EDUCATION ON CANDIDATE.CAND_NUM = EDUCATION.CAND_NUM
LEFT JOIN QUALIFICATION ON EDUCATION.QUAL_CODE = QUALIFICATION.QUAL_CODE
ORDER BY QUALIFICATION.QUAL_DESCRIPTION ASC;

--Q2
--TO CHECK WORKERS
SELECT C.COMP_NAME, CA.CAND_LNAME
FROM COMPANY C
LEFT JOIN OPENING O ON C.COMP_CODE = O.COMP_CODE
LEFT JOIN PLACEMENT P ON O.OPENING_NUM = P.OPENING_NUM
LEFT JOIN CANDIDATE CA ON P.CAND_NUM = CA.CAND_NUM
ORDER BY C.COMP_NAME ASC;

SELECT DISTINCT COMPANY.COMP_NAME
FROM COMPANY
LEFT JOIN OPENING ON COMPANY.COMP_CODE = OPENING.COMP_CODE
RIGHT JOIN PLACEMENT ON OPENING.OPENING_NUM = PLACEMENT.OPENING_NUM
ORDER BY COMPANY.COMP_NAME ASC;
--ERROR?

--Q3

SELECT CANDIDATE.CAND_NUM,CANDIDATE.CAND_LNAME,Q1.QUAL_DESCRIPTION AS Candidate_Qualification, COMPANY.COMP_CODE,COMPANY.COMP_NAME, Q2.QUAL_DESCRIPTION AS Company_Needed_Qualification
FROM CANDIDATE
LEFT JOIN EDUCATION ON CANDIDATE.CAND_NUM = EDUCATION.CAND_NUM
LEFT JOIN QUALIFICATION Q1 ON EDUCATION.QUAL_CODE = Q1.QUAL_CODE
LEFT JOIN PLACEMENT  ON CANDIDATE.CAND_NUM = PLACEMENT.CAND_NUM
LEFT JOIN OPENING ON PLACEMENT.OPENING_NUM  = OPENING.OPENING_NUM 
LEFT JOIN COMPANY ON OPENING.COMP_CODE = COMPANY.COMP_CODE
LEFT JOIN QUALIFICATION Q2 ON OPENING.QUAL_CODE = Q2.QUAL_CODE;

--Q4

SELECT CA.CAND_LNAME, CO.COURSE_DESCRIPTION, S.SESSION_STARTDATE, CO.COURSE_FEE,
    (SELECT SUM(CO.COURSE_FEE) FROM COURSE CO JOIN EDUCATION E ON CO.QUAL_CODE = E.QUAL_CODE WHERE E.CAND_NUM = CA.CAND_NUM) AS Total_Cost
FROM CANDIDATE CA
LEFT JOIN EDUCATION E ON CA.CAND_NUM = E.CAND_NUM
LEFT JOIN COURSE CO ON E.QUAL_CODE = CO.QUAL_CODE
LEFT JOIN SESSION S ON CO.COURSE_NUM = S.COURSE_NUM
ORDER BY CA.CAND_LNAME ASC;
-- needs more discussion

--Q5

SELECT CA.CAND_LNAME, E.ENROLL_FEEPAlD
FROM CANDIDATE CA
JOIN ENROLL E ON CA.CAND_NUM = E.CAND_NUM
WHERE E.ENROLL_FEEPAlD <= 0
ORDER BY CA.CAND_LNAME ASC;
-- RETURNS ZERO ROWS (ERROR?)

--Q6
SELECT COMPANY.COMP_NAME, OPENING.OPENING_DESCRIPTION, OPENING.QUAL_CODE, COUNT(PLACEMENT.PLACEMENT_NUM) AS 'Number of Placements'
FROM COMPANY
JOIN OPENING ON COMPANY.COMP_CODE = OPENING.COMP_CODE
LEFT JOIN PLACEMENT ON OPENING.OPENING_NUM = PLACEMENT.OPENING_NUM
GROUP BY OPENING.OPENING_NUM;

SELECT C.COMP_NAME, O.OPENING_DESCRIPTION, Q.QUAL_DESCRIPTION,
COUNT(P.PLACEMENT_NUM) AS SuccessfulPlacements
FROM COMPANY C
JOIN OPENING O ON C.COMP_CODE = O.COMP_CODE
JOIN QUALIFICATION Q ON O.QUAL_CODE = Q.QUAL_CODE
LEFT JOIN PLACEMENT P ON O.OPENING_NUM = P.OPENING_NUM
GROUP BY C.COMP_NAME, O.OPENING_DESCRIPTION, Q.QUAL_DESCRIPTION
ORDER BY C.COMP_NAME ASC;

--Q7
SELECT COMPANY.COMP_NAME, OPENING.QUAL_CODE, AVG(OPENING.OPENING_AVAILABLE) AS 'Average Pay'
FROM COMPANY
JOIN OPENING ON COMPANY.COMP_CODE = OPENING.COMP_CODE
GROUP BY COMPANY.COMP_NAME, OPENING.QUAL_CODE;

SELECT C.COMP_NAME, Q.QUAL_DESCRIPTION, ROUND(AVG(O.OPENING_AVAILABLE),2) AS Average_Pay
FROM COMPANY C
JOIN OPENING O ON C.COMP_CODE = O.COMP_CODE
JOIN QUALIFICATION Q ON O.QUAL_CODE = Q.QUAL_CODE
GROUP BY C.COMP_NAME, Q.QUAL_DESCRIPTION
ORDER BY C.COMP_NAME ASC;
